name: Docker Image CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
      EXPOSED_PORT: ${{vars.EXPOSED_PORT}}
      WORKING_DIR: ${{ github.repository_owner }}_${{ github.repository_name }}
      CLONE_URL: https://github.com/${{github.repository}}.git

      REGISTRY: ghcr.io
      IMAGE_NAME: ${{github.repository}}

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: BRANCH,EXPOSED_PORT,WORKING_DIR,IMAGE_NAME,REGISTRY,CLONE_URL
          script: |
            env | tee mylog.txt
            echo "Starting script..."

            cd ~
            [ -d projects ] || mkdir projects
            cd projects

            [ -d ${WORKING_DIR} ] || mkdir "${WORKING_DIR}"
            cd ${WORKING_DIR}
            echo "Changed directory to ${WORKING_DIR}."

            [ -d ${BRANCH} ] || git clone -b ${BRANCH} ${CLONE_URL} ./${BRANCH} && echo "fetching ${BRANCH} from ${CLONE_URL}"
            cd ${BRANCH}
            echo "Changed directory to ${BRANCH}."

            git fetch --all --verbose | tee mylog.txt
            git reset --hard origin/${BRANCH}
            echo "Git fetch and reset complete."

            URL_WRAPPER_IMAGE_TAG="${REGISTRY}/${IMAGE_NAME}:${BRANCH}"
            URL_WRAPPER_IMAGE_TAG=$(echo $URL_WRAPPER_IMAGE_TAG | tr '[:upper:]' '[:lower:]')
            docker pull $URL_WRAPPER_IMAGE_TAG
            echo "Docker image pulled: ${URL_WRAPPER_IMAGE_TAG}"


            echo "Updating url-wrapper service..."
            docker compose down
            docker compose up -d --build
            docker image prune -f
