name: Docker Image CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref_name }}
      EXPOSED_PORT: ${{vars.EXPOSED_PORT}}
      WORKING_DIR: ${{ github.repository_owner }}_${{ github.repository_name }}

      REGISTRY: ghcr.io
      IMAGE_NAME: ${{github.repository}}

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: BRANCH,EXPOSED_PORT,WORKING_DIR,IMAGE_NAME,REGISTRY
          script: |
            cd ~
            [ -d projects ] || mkdir projects
            cd projects
            [ -d ${WORKING_DIR} ] || mkdir "${WORKING_DIR}"
            cd ${WORKING_DIR}
            [ -d ${BRANCH} ] || git clone -b ${BRANCH} https://github.com/${IMAGE_NAME}.git ./${BRANCH} 
            cd ${BRANCH}

            git fetch --all
            git reset --hard origin/${BRANCH}

            URL_WRAPPER_IMAGE_TAG="${REGISTRY}/${IMAGE_NAME}:${BRANCH}"
            docker pull $URL_WRAPPER_IMAGE_TAG

            URL_WRAPPER_CONTAINER="url-wrapper_${BRANCH}"

            if ! docker inspect $URL_WRAPPER_CONTAINER >/dev/null 2>&1; then
              echo "Starting all services from scratch..."
              docker-compose up -d --force-recreate --remove-orphans
            else
              echo "Updating url-wrapper service..."
              docker-compose down url-wrapper
              docker-compose up -d --force-recreate --remove-orphans --no-deps url-wrapper
            fi
